/* Lazy Office-rich import helpers: PPTX/XLSX text + embedded visuals. */
async function mediaItems(zip,prefix,label,d){
  let paths=[...new Set(zip.entries.filter(e=>String(e.name||'').toLowerCase().startsWith(prefix+'media/')).map(e=>e.name))];
  const bad=paths.filter(n=>!d.officeImageMime(n));paths=paths.filter(n=>d.officeImageMime(n));
  if(paths.length>d.maxImageCount)throw d.makeAppError(label+' obsahuje '+paths.length+' vložených obrázků. Tato verze bezpečně zpracuje maximálně '+d.maxImageCount+'. Ulož materiál jako PDF nebo ho rozděl na menší části.','TOO_MANY_IMAGES');
  const items=[];
  for(const path of paths){const e=zip.entries.find(x=>x.name===path);if(!e)continue;const mime=d.officeImageMime(path),bytes=await zip.extract(e),name=path.split('/').pop()||'obrazek';items.push(await d.resizeImage(new File([bytes],name,{type:mime}),paths.length>1,Math.max(1,paths.length)))}
  return {items,unsupportedImageCount:bad.length,unsupportedImageNames:bad.slice(0,8).map(x=>x.split('/').pop())};
}

function xmlSection(xml,tag){const m=String(xml||'').match(new RegExp('<(?:c:)?'+tag+'\\b[^>]*>([\\s\\S]*?)<\\/(?:c:)?'+tag+'>','i'));return m?m[1]:''}
function xmlValues(xml,d){const pts=[...String(xml||'').matchAll(/<(?:c:)?pt\b[^>]*>[\s\S]*?<(?:c:)?v>([\s\S]*?)<\/(?:c:)?v>[\s\S]*?<\/(?:c:)?pt>/gi)].map(m=>d.xmlUnescape(m[1]).trim());if(pts.length)return pts;return [...String(xml||'').matchAll(/<(?:c:)?v>([\s\S]*?)<\/(?:c:)?v>/gi)].map(m=>d.xmlUnescape(m[1]).trim())}
function chartKind(xml){const raw=(String(xml||'').match(/<(?:c:)?(barChart|lineChart|pieChart|doughnutChart|scatterChart|areaChart|radarChart|bubbleChart|stockChart)\b/i)||[])[1]||'chart';return {raw,type:raw==='barChart'?'bar':raw==='lineChart'?'line':/^(?:pieChart|doughnutChart)$/.test(raw)?'pie':raw==='scatterChart'?'scatter':null}}
function chartTitle(xml,d,fallback){const title=xmlSection(xml,'title');const a=[...title.matchAll(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/gi)].map(m=>d.xmlUnescape(m[1]).trim()).filter(Boolean);return a.join(' ').trim()||fallback}
function chartSpec(xml,d,index,label){
  const kind=chartKind(xml);if(!kind.type||kind.type==='scatter')return null;
  const series=[];let labels=[];const blocks=[...String(xml||'').matchAll(/<(?:c:)?ser\b[^>]*>([\s\S]*?)<\/(?:c:)?ser>/gi)].map(m=>m[1]);
  for(let i=0;i<blocks.length&&i<8;i++){const block=blocks[i],vals=xmlValues(xmlSection(block,'val'),d).slice(0,60).map(Number);if(!vals.some(Number.isFinite))continue;const cats=xmlValues(xmlSection(block,'cat'),d).slice(0,60);if(!labels.length&&cats.length)labels=cats;const tx=xmlValues(xmlSection(block,'tx'),d).filter(Boolean);series.push({name:(tx[0]||('Řada '+(i+1))).slice(0,60),values:vals.map(v=>Number.isFinite(v)?v:null)})}
  if(!series.length)return null;const n=Math.max(...series.map(x=>x.values.length));if(!labels.length)labels=Array.from({length:n},(_,i)=>String(i+1));
  return {type:kind.type,title:chartTitle(xml,d,label+' graf '+index),labels:labels.slice(0,n),series};
}
function chartTechnicalNote(xml,d,index){const kind=chartKind(xml).raw,refs=[...String(xml||'').matchAll(/<(?:c:)?f>([\s\S]*?)<\/(?:c:)?f>/gi)].map(m=>d.xmlUnescape(m[1]).trim()).filter(Boolean),vals=[...String(xml||'').matchAll(/<(?:c:)?v>([\s\S]*?)<\/(?:c:)?v>/gi)].map(m=>d.xmlUnescape(m[1]).trim()).filter(Boolean).slice(0,120);return 'Graf '+index+' ('+kind+'): zdrojové oblasti '+(refs.slice(0,12).join('; ')||'neuvedeny')+(vals.length?' | uložené hodnoty: '+vals.join(', '):'')}
async function chartBlock(zip,prefix,d,label){const charts=zip.entries.filter(e=>new RegExp('^'+prefix.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'charts/chart\\d+\\.xml$','i').test(e.name));if(!charts.length)return {count:0,text:''};const notes=[],markers=[];for(let i=0;i<charts.length;i++){const xml=new TextDecoder().decode(await zip.extract(charts[i]));notes.push(chartTechnicalNote(xml,d,i+1));const spec=chartSpec(xml,d,i+1,label);if(spec)markers.push('[[EDU_CHART|'+JSON.stringify(spec)+']]')}return {count:charts.length,text:'NATIVNÍ GRAFY V '+label+' — datový přepis pro AI a deterministický renderer:\n'+notes.join('\n')+(markers.length?'\n'+markers.join('\n'):'')}}
async function diagramBlock(zip,prefix,d,label){const diagrams=zip.entries.filter(e=>new RegExp('^'+prefix.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'diagrams/data\\d+\\.xml$','i').test(e.name));if(!diagrams.length)return {count:0,text:''};const notes=[];for(let i=0;i<diagrams.length;i++){const xml=new TextDecoder().decode(await zip.extract(diagrams[i])),labels=[...xml.matchAll(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/gi)].map(m=>d.xmlUnescape(m[1]).trim()).filter(Boolean);notes.push('Diagram '+(i+1)+': '+(labels.slice(0,80).join(' | ')||'bez čitelného textu'))}return {count:diagrams.length,text:'SMARTART / NATIVNÍ DIAGRAMY V '+label+' — textový přepis pro AI:\n'+notes.join('\n')}}
function attr(xml,name){const m=String(xml||'').match(new RegExp('\\b'+name+'="([^"]*)"','i'));return m?m[1]:''}
function pptShapeText(xml,d){return [...String(xml||'').matchAll(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/gi)].map(m=>d.xmlUnescape(m[1]).trim()).filter(Boolean).join(' ').slice(0,400)}
function pptXfrm(xml){const xfrm=(String(xml||'').match(/<a:xfrm\b[\s\S]*?<\/a:xfrm>/i)||[])[0]||'';const off=(xfrm.match(/<a:off\b[^>]*>/i)||[])[0]||'',ext=(xfrm.match(/<a:ext\b[^>]*>/i)||[])[0]||'';return {x:Number(attr(off,'x'))||0,y:Number(attr(off,'y'))||0,cx:Number(attr(ext,'cx'))||0,cy:Number(attr(ext,'cy'))||0,rot:Number(attr((xfrm.match(/<a:xfrm\b[^>]*>/i)||[])[0]||'','rot'))||0}}
function pptShapeSpec(xml,d,kind='shape'){const g=(String(xml||'').match(/<a:prstGeom\b[^>]*>/i)||[])[0]||'',prst=attr(g,'prst')|| (kind==='connector'?'line':'rect'),xf=pptXfrm(xml),txt=pptShapeText(xml,d);if(!(xf.cx||xf.cy))return null;return {kind,type:prst,x:xf.x,y:xf.y,w:xf.cx,h:xf.cy,rot:xf.rot,text:txt}}
async function pptDrawingBlock(zip,d){
 const slides=zip.entries.filter(e=>/^ppt\/slides\/slide\d+\.xml$/i.test(e.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));if(!slides.length)return {count:0,text:'',unsupported:0};let size={cx:12192000,cy:6858000};const pe=zip.entries.find(e=>/^ppt\/presentation\.xml$/i.test(e.name));if(pe){const px=new TextDecoder().decode(await zip.extract(pe)),tag=(px.match(/<p:sldSz\b[^>]*>/i)||[])[0]||'';size={cx:Number(attr(tag,'cx'))||size.cx,cy:Number(attr(tag,'cy'))||size.cy}}
 const markers=[],notes=[];let total=0,unsupported=0;
 for(let si=0;si<slides.length;si++){const xml=new TextDecoder().decode(await zip.extract(slides[si])),shapes=[];for(const m of xml.matchAll(/<p:sp\b[\s\S]*?<\/p:sp>/gi)){const x=pptShapeSpec(m[0],d,'shape');if(x){shapes.push(x);total++}}for(const m of xml.matchAll(/<p:cxnSp\b[\s\S]*?<\/p:cxnSp>/gi)){const x=pptShapeSpec(m[0],d,'connector');if(x){shapes.push(x);total++}}unsupported+=(xml.match(/<p:graphicFrame\b/gi)||[]).length;if(shapes.length){const spec={title:'PPTX snímek '+(si+1)+' — nativní tvary',width:size.cx,height:size.cy,shapes:shapes.slice(0,160)};markers.push('[[EDU_OFFICE|'+JSON.stringify(spec)+']]');notes.push('Snímek '+(si+1)+': '+shapes.length+' rekonstruovatelných nativních tvarů/spojnic.')}}
 return {count:total,unsupported,text:markers.length?'NATIVNÍ DRAWINGML TVARY V PPTX — deterministická rekonstrukce geometrie a textu:\n'+notes.join('\n')+'\n'+markers.join('\n'):''};
}
async function wordDrawingBlock(zip,d){
 const e=zip.entries.find(x=>/^word\/document\.xml$/i.test(x.name));if(!e)return {count:0,text:'',unsupported:0};const xml=new TextDecoder().decode(await zip.extract(e)),blocks=[...xml.matchAll(/<wp:(?:anchor|inline)\b[\s\S]*?<\/wp:(?:anchor|inline)>/gi)].map(m=>m[0]);if(!blocks.length)return {count:0,text:'',unsupported:0};const shapes=[];let seq=0,unsupported=0;for(const b of blocks){if(/<pic:pic\b/i.test(b)){continue}const ext=(b.match(/<wp:extent\b[^>]*>/i)||[])[0]||'',w=Number(attr(ext,'cx'))||1800000,h=Number(attr(ext,'cy'))||900000,offs=[...b.matchAll(/<wp:posOffset>(-?\d+)<\/wp:posOffset>/gi)].map(m=>Number(m[1]));const type=attr((b.match(/<a:prstGeom\b[^>]*>/i)||[])[0]||'','prst')||'rect',txt=[...b.matchAll(/<(?:w|a):t\b[^>]*>([\s\S]*?)<\/(?:w|a):t>/gi)].map(m=>d.xmlUnescape(m[1]).trim()).filter(Boolean).join(' ').slice(0,400);if(!txt&&!/<wps:wsp\b|<a:prstGeom\b/i.test(b)){unsupported++;continue}const x=Number.isFinite(offs[0])?offs[0]:500000+(seq%2)*5000000,y=Number.isFinite(offs[1])?offs[1]:500000+Math.floor(seq/2)*1600000;seq++;shapes.push({kind:'shape',type,x,y,w,h,text:txt})}if(!shapes.length)return {count:0,text:'',unsupported};const maxX=Math.max(10000000,...shapes.map(x=>x.x+x.w+300000)),maxY=Math.max(14000000,...shapes.map(x=>x.y+x.h+300000)),spec={title:'DOCX — nativní DrawingML tvary',width:maxX,height:maxY,shapes:shapes.slice(0,160)};return {count:shapes.length,unsupported,text:'NATIVNÍ DRAWINGML TVARY V DOCX — deterministická rekonstrukce geometrie a textu:\n[[EDU_OFFICE|'+JSON.stringify(spec)+']]'}
}
function xdrNum(block,tag){const m=String(block||'').match(new RegExp('<xdr:'+tag+'>(-?\\d+)<\\/xdr:'+tag+'>','i'));return m?Number(m[1]):0}
async function xlsxDrawingBlock(zip,d){const entries=zip.entries.filter(e=>/^xl\/drawings\/drawing\d+\.xml$/i.test(e.name));if(!entries.length)return {count:0,text:'',unsupported:0};const markers=[],notes=[];let count=0,unsupported=0;for(let ei=0;ei<entries.length;ei++){const xml=new TextDecoder().decode(await zip.extract(entries[ei])),shapes=[];for(const m of xml.matchAll(/<xdr:(?:twoCellAnchor|oneCellAnchor)\b[\s\S]*?<\/xdr:(?:twoCellAnchor|oneCellAnchor)>/gi)){const b=m[0];if(/<xdr:pic\b/i.test(b))continue;if(/<xdr:graphicFrame\b/i.test(b)){unsupported++;continue}const from=(b.match(/<xdr:from>[\s\S]*?<\/xdr:from>/i)||[])[0]||'',to=(b.match(/<xdr:to>[\s\S]*?<\/xdr:to>/i)||[])[0]||'',col=xdrNum(from,'col'),row=xdrNum(from,'row'),col2=to?xdrNum(to,'col'):col+2,row2=to?xdrNum(to,'row'):row+3,x=col*110+xdrNum(from,'colOff')/9000,y=row*34+xdrNum(from,'rowOff')/9000,w=Math.max(80,(col2-col)*110+(xdrNum(to,'colOff')-xdrNum(from,'colOff'))/9000),h=Math.max(36,(row2-row)*34+(xdrNum(to,'rowOff')-xdrNum(from,'rowOff'))/9000),type=attr((b.match(/<a:prstGeom\b[^>]*>/i)||[])[0]||'','prst')||(/<xdr:cxnSp\b/i.test(b)?'line':'rect'),txt=[...b.matchAll(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/gi)].map(x=>d.xmlUnescape(x[1]).trim()).filter(Boolean).join(' ').slice(0,400);if(!/<xdr:(?:sp|cxnSp)\b/i.test(b)){unsupported++;continue}shapes.push({kind:/<xdr:cxnSp\b/i.test(b)?'connector':'shape',type,x,y,w,h,text:txt});count++}if(shapes.length){const maxX=Math.max(1000,...shapes.map(x=>x.x+x.w+30)),maxY=Math.max(600,...shapes.map(x=>x.y+x.h+30)),spec={title:'XLSX kresba '+(ei+1),width:maxX,height:maxY,shapes:shapes.slice(0,160)};markers.push('[[EDU_OFFICE|'+JSON.stringify(spec)+']]');notes.push('Kresba '+(ei+1)+': '+shapes.length+' tvarů/spojnic.')}}return {count,unsupported,text:markers.length?'NATIVNÍ DRAWINGML TVARY V XLSX — deterministická rekonstrukce:\n'+notes.join('\n')+'\n'+markers.join('\n'):''}}
export async function readDocxNativeObjects(zip,d){const charts=await chartBlock(zip,'word/',d,'DOCX'),diagrams=await diagramBlock(zip,'word/',d,'DOCX'),drawings=await wordDrawingBlock(zip,d);const review=drawings.unsupported?'OFFICE_VISUAL_REVIEW: DOCX obsahuje '+drawings.unsupported+' nativních objektů, které nelze bezpečně rekonstruovat z DrawingML. Pokud je vzhled součástí zadání, použij PDF nebo snímek.':'';return {text:[charts.text,diagrams.text,drawings.text,review].filter(Boolean).join('\n\n'),chartCount:charts.count,diagramCount:diagrams.count,drawingCount:drawings.count,unsupportedNativeCount:drawings.unsupported}}
export async function readPptxRich(file,d){
  const zip=await d.readZipEntries(file,'.pptx'),slides=zip.entries.filter(e=>/^ppt\/slides\/slide\d+\.xml$/i.test(e.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));
  if(!slides.length)throw new Error('V .pptx se nenašly čitelné snímky.');
  const chunks=[];
  for(let i=0;i<slides.length;i++){const xml=new TextDecoder().decode(await zip.extract(slides[i])),text=d.officeBlockText(xml,/<a:p\b[\s\S]*?<\/a:p>/g);if(text.trim())chunks.push('Snímek '+(i+1)+':\n'+text.trim())}
  const nativeCharts=await chartBlock(zip,'ppt/',d,'PPTX');if(nativeCharts.text)chunks.push(nativeCharts.text);
  const nativeDiagrams=await diagramBlock(zip,'ppt/',d,'PPTX');if(nativeDiagrams.text)chunks.push(nativeDiagrams.text);
  const drawings=await pptDrawingBlock(zip,d);if(drawings.text)chunks.push(drawings.text);if(drawings.unsupported)chunks.push('OFFICE_VISUAL_REVIEW: PPTX obsahuje '+drawings.unsupported+' nativních grafických rámců (např. SmartArt/graf/tabulka/OLE), které nelze zaručeně pixelově rekonstruovat bez Office renderovacího enginu. Jejich data/text jsou zpracovány samostatnými cestami; pokud je přesný vzhled součástí úlohy, vyžaduj PDF nebo snímek.');
  const text=chunks.join('\n\n').trim(),media=await mediaItems(zip,'ppt/','PPTX',d);if(!text&&!media.items.length)throw new Error('V .pptx se nenašel čitelný text ani podporované vložené obrázky.');return {text,...media,chartCount:nativeCharts.count,diagramCount:nativeDiagrams.count,drawingCount:drawings.count,unsupportedNativeCount:drawings.unsupported};
}
export async function readXlsxRich(file,d){
  const zip=await d.readZipEntries(file,'.xlsx');let shared=[];const xt=xml=>[...String(xml||'').matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(m=>d.xmlUnescape(m[1])).join(''),ss=zip.entries.find(e=>/^xl\/sharedStrings\.xml$/i.test(e.name));
  if(ss){const xml=new TextDecoder().decode(await zip.extract(ss));shared=[...xml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>xt(m[1]))}
  const sheets=zip.entries.filter(e=>/^xl\/worksheets\/sheet\d+\.xml$/i.test(e.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));if(!sheets.length)throw new Error('V .xlsx se nenašly čitelné listy.');
  const col=ref=>{let n=0;for(const ch of String(ref||'').replace(/\d/g,''))n=n*26+ch.charCodeAt(0)-64;return Math.max(0,n-1)},cell=c=>{const type=(c.match(/\bt="([^"]+)"/)||[])[1]||'',f=(c.match(/<f[^>]*>([\s\S]*?)<\/f>/)||[])[1];if(type==='inlineStr')return xt(c);const v=(c.match(/<v>([\s\S]*?)<\/v>/)||[])[1];let x=v==null?'':type==='s'?(shared[Number(v)]||''):d.xmlUnescape(v);if(f)x='='+d.xmlUnescape(f)+(x?' → '+x:'');return x};
  const out=[];for(let i=0;i<sheets.length;i++){const xml=new TextDecoder().decode(await zip.extract(sheets[i])),rows=[...xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)].map(r=>{const a=[];for(const c of r[1].matchAll(/<c\b[^>]*>[\s\S]*?<\/c>/g)){const ref=(c[0].match(/\br="([A-Z]+\d+)"/)||[])[1],idx=ref?col(ref):a.length;while(a.length<idx)a.push('');a[idx]=cell(c[0])}return a.join('\t').replace(/\t+$/,'')}).filter(r=>r.trim());if(rows.length)out.push('List '+(i+1)+':\n'+rows.join('\n'))}
  let text=out.join('\n\n').trim();const nativeCharts=await chartBlock(zip,'xl/',d,'XLSX');if(nativeCharts.text)text+=(text?'\n\n':'')+nativeCharts.text;const drawings=await xlsxDrawingBlock(zip,d);if(drawings.text)text+=(text?'\n\n':'')+drawings.text;if(drawings.unsupported)text+=(text?'\n\n':'')+'OFFICE_VISUAL_REVIEW: XLSX obsahuje '+drawings.unsupported+' nativních kreslicích objektů/rámců, které nelze bezpečně rekonstruovat; pro přesný vzhled použij PDF nebo snímek.';
  const media=await mediaItems(zip,'xl/','XLSX',d);if(!text&&!media.items.length)throw new Error('V .xlsx se nenašel čitelný obsah ani podporované vložené obrázky.');return {text,...media,chartCount:nativeCharts.count,drawingCount:drawings.count,unsupportedNativeCount:drawings.unsupported};
}
