/* Diferenciator 1.3.31 - bounded school reaction balancer and simple stoichiometry. */
const txt=(v,n=180)=>String(v??'').trim().slice(0,n),gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){const t=a%b;a=b;b=t}return a||1n},lcm=(a,b)=>a/gcd(a,b)*b;
class Q{constructor(n=0n,d=1n){if(d===0n)throw Error('Nulový jmenovatel.');if(d<0n){n=-n;d=-d}const g=gcd(n,d);this.n=n/g;this.d=d/g}add(b){b=Q.of(b);return new Q(this.n*b.d+b.n*this.d,this.d*b.d)}sub(b){b=Q.of(b);return new Q(this.n*b.d-b.n*this.d,this.d*b.d)}mul(b){b=Q.of(b);return new Q(this.n*b.n,this.d*b.d)}div(b){b=Q.of(b);if(b.n===0n)throw Error('Dělení nulou.');return new Q(this.n*b.d,this.d*b.n)}neg(){return new Q(-this.n,this.d)}zero(){return this.n===0n}static of(x){return x instanceof Q?x:new Q(BigInt(x),1n)}}
const WEIGHTS=Object.freeze({H:1.008,He:4.0026,Li:6.94,Be:9.0122,B:10.81,C:12.011,N:14.007,O:15.999,F:18.998,Ne:20.18,Na:22.99,Mg:24.305,Al:26.982,Si:28.085,P:30.974,S:32.06,Cl:35.45,Ar:39.948,K:39.098,Ca:40.078,Sc:44.956,Ti:47.867,V:50.942,Cr:51.996,Mn:54.938,Fe:55.845,Co:58.933,Ni:58.693,Cu:63.546,Zn:65.38,Ga:69.723,Ge:72.63,As:74.922,Se:78.971,Br:79.904,Kr:83.798,Rb:85.468,Sr:87.62,Ag:107.868,Cd:112.414,Sn:118.71,I:126.904,Ba:137.327,Pt:195.084,Au:196.967,Hg:200.592,Pb:207.2});
const ELEMENTS=new Set('H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og'.split(' '));
function addCounts(to,from,m=1){for(const [e,n] of Object.entries(from))to[e]=(to[e]||0)+n*m;return to}
function parseGroup(s,start=0,close=''){const counts={};let i=start;while(i<s.length){const c=s[i];if(close&&c===close)return {counts,i:i+1};if(c==='('||c==='['||c==='{'){const pair=c==='('?')':c==='['?']':'}',g=parseGroup(s,i+1,pair);i=g.i;const m=s.slice(i).match(/^\d+/),k=m?Number(m[0]):1;if(m)i+=m[0].length;addCounts(counts,g.counts,k);continue}if(/[A-Z]/.test(c)){const m=s.slice(i).match(/^[A-Z][a-z]?/),el=m[0];if(!ELEMENTS.has(el))throw Error('Neznámý symbol prvku: '+el);i+=el.length;const q=s.slice(i).match(/^\d+/),k=q?Number(q[0]):1;if(q)i+=q[0].length;if(!Number.isInteger(k)||k<1||k>100000)throw Error('Neplatný stechiometrický index.');counts[el]=(counts[el]||0)+k;continue}throw Error('Nepodporovaný znak ve vzorci: '+c)}if(close)throw Error('Neuzavřená závorka ve vzorci.');return {counts,i}}
function splitCharge(raw){let s=raw.replace(/\s+/g,'').replace(/\((?:aq|s|l|g)\)$/i,'');if(/^e\^-$/i.test(s))return {formula:'',charge:-1,electron:true};const m=s.match(/\^(\d*)([+-])$/);if(!m)return {formula:s,charge:0,electron:false};const mag=Number(m[1]||1);return {formula:s.slice(0,m.index),charge:m[2]==='+'?mag:-mag,electron:false}}
export function parseChemicalFormula(raw){const source=txt(raw,120),c=splitCharge(source);if(c.electron)return {formula:'e^-',atoms:{},charge:-1,molarMass:0};if(!c.formula)throw Error('Prázdný chemický vzorec.');const atoms={};for(const part of c.formula.split(/[·.]/)){if(!part)throw Error('Neplatný hydrátový zápis.');const m=part.match(/^(\d+)(.+)$/),factor=m?Number(m[1]):1,body=m?m[2]:part;if(!Number.isInteger(factor)||factor<1||factor>1000)throw Error('Neplatný násobek hydrátu.');const p=parseGroup(body);if(p.i!==body.length)throw Error('Vzorec nebyl zpracován celý.');addCounts(atoms,p.counts,factor)}let molarMass=0;for(const [e,n] of Object.entries(atoms)){if(WEIGHTS[e]==null){molarMass=NaN;break}molarMass+=WEIGHTS[e]*n}return {formula:source,atoms,charge:c.charge,molarMass}}
function splitTerms(side){const out=[];let cur='',depth=0;for(let i=0;i<side.length;i++){const c=side[i];if('([{'.includes(c))depth++;if(')]}'.includes(c))depth--;if(c==='+'&&depth===0){if(/\^\d*\s*$/.test(cur)){cur+=c;continue}if(cur.trim())out.push(cur.trim());cur='';continue}cur+=c}if(cur.trim())out.push(cur.trim());return out}
function parseTerm(term){const m=term.match(/^\s*(\d+)\s*(.+)$/),given=m?Number(m[1]):null,formula=(m?m[2]:term).trim(),parsed=parseChemicalFormula(formula);return {raw:term,formula:parsed.formula,atoms:parsed.atoms,charge:parsed.charge,molarMass:parsed.molarMass,givenCoefficient:given}}
export function parseReaction(equation){const source=txt(equation,500),parts=source.split(/\s*(?:->|→|=)\s*/);if(parts.length!==2)throw Error('Rovnice musí obsahovat právě jednu šipku -> nebo →.');const left=splitTerms(parts[0]).map(parseTerm),right=splitTerms(parts[1]).map(parseTerm);if(!left.length||!right.length)throw Error('Rovnice musí mít reaktanty i produkty.');if(left.length+right.length>24)throw Error('Rovnice obsahuje příliš mnoho částic.');return {source,left,right}}
function rrefNullspace(matrix){const a=matrix.map(r=>r.map(x=>new Q(BigInt(x)))),rows=a.length,cols=a[0]?.length||0,piv=[],free=[];let r=0;for(let c=0;c<cols&&r<rows;c++){let q=r;while(q<rows&&a[q][c].zero())q++;if(q===rows)continue;[a[r],a[q]]=[a[q],a[r]];const d=a[r][c];a[r]=a[r].map(x=>x.div(d));for(let i=0;i<rows;i++)if(i!==r&&!a[i][c].zero()){const f=a[i][c];a[i]=a[i].map((x,j)=>x.sub(f.mul(a[r][j])))}piv.push(c);r++}for(let c=0;c<cols;c++)if(!piv.includes(c))free.push(c);if(!free.length)throw Error('Rovnice nemá nenulové bilanční řešení.');return free.map(fc=>{const v=Array.from({length:cols},()=>new Q(0n));v[fc]=new Q(1n);for(let i=piv.length-1;i>=0;i--){const pc=piv[i];let sum=new Q(0n);for(const f of free)sum=sum.add(a[i][f].mul(v[f]));for(const later of piv.slice(i+1))sum=sum.add(a[i][later].mul(v[later]));v[pc]=sum.neg()}return v})}
function integers(v){let d=1n;for(const x of v)d=lcm(d,x.d);let a=v.map(x=>x.n*(d/x.d));let g=0n;for(const x of a)g=gcd(g,x);a=a.map(x=>x/g);if(a.every(x=>x<0n))a=a.map(x=>-x);return a}
function positiveVector(basis){if(basis.length!==1)throw Error('Rovnice není jednoznačně vyčíslitelná; doplň chybějící látku nebo zadej očekávané koeficienty.');const a=integers(basis[0]);if(a.every(x=>x>0n)||a.every(x=>x<0n))return a[0]<0n?a.map(x=>-x):a;throw Error('Bilanční řešení nevede na kladné koeficienty.')}
function constrainedVector(values,rows,size){if(!Array.isArray(values))throw Error('Rovnice není jednoznačně vyčíslitelná; doplň chybějící látku nebo zadej očekávané koeficienty.');if(values.length!==size)throw Error('Očekávané koeficienty mají nesprávný počet položek.');const a=values.map(x=>{const n=Number(x);if(!Number.isSafeInteger(n)||n<1)throw Error('Očekávané koeficienty musí být kladná celá čísla.');return BigInt(n)});for(const row of rows){let sum=0n;for(let i=0;i<row.length;i++)sum+=BigInt(row[i])*a[i];if(sum!==0n)throw Error('Zadané koeficienty nesplňují atomovou nebo nábojovou bilanci.')}return coeffGcd(a)}
function coeffGcd(a){let g=0n;for(const x of a)g=gcd(g,x);return a.map(x=>x/g)}
export function balanceReaction(specOrEquation={}){const spec=typeof specOrEquation==='string'?{equation:specOrEquation}:specOrEquation,errors=[];try{const r=parseReaction(spec.equation||''),all=[...r.left,...r.right],elements=[...new Set(all.flatMap(x=>Object.keys(x.atoms)))].sort(),hasCharge=all.some(x=>x.charge!==0),rows=elements.map(e=>all.map((x,i)=>(i<r.left.length?1:-1)*(x.atoms[e]||0)));if(hasCharge)rows.push(all.map((x,i)=>(i<r.left.length?1:-1)*x.charge));const basis=rrefNullspace(rows),given=all.map(x=>x.givenCoefficient),constraint=Array.isArray(spec.expectedCoefficients)?spec.expectedCoefficients:(given.every(x=>x!=null)?given:null);const coeff=(basis.length===1?coeffGcd(positiveVector(basis)):constrainedVector(constraint,rows,all.length)).map(Number);if(coeff.some(x=>!Number.isSafeInteger(x)||x<1))throw Error('Koeficienty jsou mimo bezpečný rozsah.');if(given.some(x=>x!=null)){const ratios=given.map((x,i)=>x==null?null:x/coeff[i]).filter(x=>x!=null),base=ratios[0];if(ratios.some(x=>Math.abs(x-base)>1e-10))errors.push('Koeficienty zadané v rovnici nejsou ve správném vzájemném poměru.')}if(Array.isArray(spec.expectedCoefficients)&&(spec.expectedCoefficients.length!==coeff.length||spec.expectedCoefficients.some((x,i)=>Number(x)!==coeff[i])))errors.push('Očekávané koeficienty nesouhlasí s lokálním vyčíslením.');const atomBalance={};for(const e of elements){const l=r.left.reduce((s,x,i)=>s+(x.atoms[e]||0)*coeff[i],0),rr=r.right.reduce((s,x,i)=>s+(x.atoms[e]||0)*coeff[r.left.length+i],0);atomBalance[e]={left:l,right:rr}}const chargeBalance=hasCharge?{left:r.left.reduce((s,x,i)=>s+x.charge*coeff[i],0),right:r.right.reduce((s,x,i)=>s+x.charge*coeff[r.left.length+i],0)}:null;return {...r,coefficients:coeff,leftCoefficients:coeff.slice(0,r.left.length),rightCoefficients:coeff.slice(r.left.length),elements,atomBalance,chargeBalance,errors}}catch(e){return {source:txt(spec.equation,500),left:[],right:[],coefficients:[],leftCoefficients:[],rightCoefficients:[],elements:[],atomBalance:{},chargeBalance:null,errors:[e.message]}}}
const NA=6.02214076e23;
function speciesIndex(b,species){const key=String(species||'').replace(/\s+/g,''),all=[...b.left,...b.right];return all.findIndex(x=>x.formula.replace(/\s+/g,'')===key)}
function toMol(amount,unit,sp){const n=Number(amount);if(!Number.isFinite(n)||n<0)throw Error('Stechiometrické množství musí být nezáporné číslo.');const u=String(unit||'mol').toLowerCase();if(u==='mol')return n;if(u==='mmol')return n/1000;if(u==='g'){if(!Number.isFinite(sp.molarMass)||sp.molarMass<=0)throw Error('Pro převod gramů chybí podporovaná molární hmotnost.');return n/sp.molarMass}if(['particles','molecules','částic','castic'].includes(u))return n/NA;throw Error('Podporované jednotky jsou mol, mmol, g a particles/molecules.')}
function fromMol(mol,unit,sp){const u=String(unit||'mol').toLowerCase();if(u==='mol')return mol;if(u==='mmol')return mol*1000;if(u==='g'){if(!Number.isFinite(sp.molarMass)||sp.molarMass<=0)throw Error('Pro převod gramů chybí podporovaná molární hmotnost.');return mol*sp.molarMass}if(['particles','molecules','částic','castic'].includes(u))return mol*NA;throw Error('Podporované jednotky jsou mol, mmol, g a particles/molecules.')}
export function reactionStoichiometry(spec={}){const b=balanceReaction(spec),errors=[...b.errors];if(!b.coefficients.length)return {...b,stoichiometry:null,errors};const st=spec.stoichiometry;if(!st)return {...b,stoichiometry:null,errors};try{const gi=speciesIndex(b,st.given?.species),fi=speciesIndex(b,st.find?.species);if(gi<0||fi<0)throw Error('Stechiometrie odkazuje na částici, která není v rovnici.');const all=[...b.left,...b.right],gmol=toMol(st.given.amount,st.given.unit,all[gi]),fmol=gmol*b.coefficients[fi]/b.coefficients[gi],value=fromMol(fmol,st.find.unit,all[fi]),result={given:{...st.given,moles:gmol},find:{...st.find,value,moles:fmol},ratio:[b.coefficients[gi],b.coefficients[fi]]};if(st.expected!=null&&(!Number.isFinite(Number(st.expected))||Math.abs(value-Number(st.expected))>Math.max(1e-9,Math.abs(value)*1e-6)))errors.push('Očekávaný stechiometrický výsledek nesouhlasí s lokálním výpočtem.');return {...b,stoichiometry:result,errors}}catch(e){errors.push(e.message);return {...b,stoichiometry:null,errors}}}
