/* Diferenciator 1.3.29 - deterministic gymnasium CAS verifier. No eval, no network. */
const FN=new Set(['sin','cos','tan','asin','acos','atan','sqrt','abs','ln','log','exp']);
const CONST=Object.freeze({pi:Math.PI,e:Math.E});
function tokenize(src){const out=[];let i=0,s=String(src||'').replace(/[−–—]/g,'-').replace(/π/g,'pi').replace(/√/g,'sqrt');while(i<s.length){if(/\s/.test(s[i])){i++;continue}const n=s.slice(i).match(/^(?:\d+(?:[.,]\d*)?|[.,]\d+)(?:e[+-]?\d+)?/i);if(n){out.push(['n',Number(n[0].replace(',','.'))]);i+=n[0].length;continue}const id=s.slice(i).match(/^[A-Za-z_][A-Za-z0-9_]*/);if(id){out.push(['id',id[0]]);i+=id[0].length;continue}if('+-*/^(),='.includes(s[i])){out.push([s[i],s[i]]);i++;continue}throw new Error('Nepodporovaný znak v CAS: '+s[i])}return out}
function parse(src){const t=tokenize(src),p={i:0};const peek=()=>t[p.i]?.[0],eat=k=>peek()===k?(p.i++,t[p.i-1]):null;function primary(){if(eat('(')){const v=add();if(!eat(')'))throw Error('Chybí )');return v}const n=eat('n');if(n)return {k:'n',v:n[1]};const id=eat('id');if(id){const name=id[1];if(eat('(')){const args=[];if(peek()!==')'){do{args.push(add())}while(eat(','))}if(!eat(')'))throw Error('Chybí ) u funkce');return {k:'f',name,args}}return {k:'v',name}}throw Error('Neplatný výraz')}function unary(){if(eat('+'))return unary();if(eat('-'))return {k:'u',op:'-',a:unary()};return primary()}function pow(){let a=unary();if(eat('^'))a={k:'b',op:'^',a,b:pow()};return a}function mul(){let a=pow();for(;;){if(eat('*'))a={k:'b',op:'*',a,b:pow()};else if(eat('/'))a={k:'b',op:'/',a,b:pow()};else if(['n','id','('].includes(peek()))a={k:'b',op:'*',a,b:pow()};else return a}}function add(){let a=mul();for(;;){if(eat('+'))a={k:'b',op:'+',a,b:mul()};else if(eat('-'))a={k:'b',op:'-',a,b:mul()};else return a}}const ast=add();if(p.i!==t.length)throw Error('Neočekávaný token');return ast}
function val(ast,vars={}){switch(ast.k){case'n':return ast.v;case'v':if(Object.hasOwn(CONST,ast.name))return CONST[ast.name];if(Object.hasOwn(vars,ast.name))return Number(vars[ast.name]);throw Error('Neznámá proměnná '+ast.name);case'u':return -val(ast.a,vars);case'b':{const a=val(ast.a,vars),b=val(ast.b,vars);return ast.op==='+'?a+b:ast.op==='-'?a-b:ast.op==='*'?a*b:ast.op==='/'?a/b:Math.pow(a,b)}case'f':{if(!FN.has(ast.name))throw Error('Nepodporovaná funkce '+ast.name);const a=ast.args.map(x=>val(x,vars));if(ast.name==='ln')return Math.log(a[0]);if(ast.name==='log')return a.length>1?Math.log(a[0])/Math.log(a[1]):Math.log10(a[0]);return Math[ast.name](...a)}default:throw Error('Neplatný AST')}}
const N=v=>({k:'n',v}),V=name=>({k:'v',name}),B=(op,a,b)=>({k:'b',op,a,b}),F=(name,...args)=>({k:'f',name,args});
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function simplify(a){if(!a)return a;if(a.k==='u'){const x=simplify(a.a);return x.k==='n'?N(-x.v):x.k==='u'?simplify(x.a):{...a,a:x}}if(a.k==='f'){const args=a.args.map(simplify);if(args.every(x=>x.k==='n'))try{return N(val({k:'f',name:a.name,args}))}catch{}return {...a,args}}if(a.k!=='b')return a;let x=simplify(a.a),y=simplify(a.b);if(x.k==='n'&&y.k==='n')try{const z=val(B(a.op,x,y));if(Number.isFinite(z))return N(z)}catch{}if(a.op==='+'){if(y.k==='n'&&y.v===0)return x;if(x.k==='n'&&x.v===0)return y}if(a.op==='-'){if(y.k==='n'&&y.v===0)return x;if(same(x,y))return N(0)}if(a.op==='*'){if((x.k==='n'&&x.v===0)||(y.k==='n'&&y.v===0))return N(0);if(x.k==='n'&&x.v===1)return y;if(y.k==='n'&&y.v===1)return x}if(a.op==='/'){if(x.k==='n'&&x.v===0)return N(0);if(y.k==='n'&&y.v===1)return x;if(same(x,y))return N(1)}if(a.op==='^'){if(y.k==='n'&&y.v===1)return x;if(y.k==='n'&&y.v===0)return N(1)}return B(a.op,x,y)}
function derivative(a,x='x'){a=simplify(a);if(a.k==='n')return N(0);if(a.k==='v')return N(a.name===x?1:0);if(a.k==='u')return simplify({k:'u',op:'-',a:derivative(a.a,x)});if(a.k==='b'){const u=a.a,v=a.b,du=derivative(u,x),dv=derivative(v,x);if(a.op==='+')return simplify(B('+',du,dv));if(a.op==='-')return simplify(B('-',du,dv));if(a.op==='*')return simplify(B('+',B('*',du,v),B('*',u,dv)));if(a.op==='/')return simplify(B('/',B('-',B('*',du,v),B('*',u,dv)),B('^',v,N(2))));if(a.op==='^'&&v.k==='n')return simplify(B('*',B('*',N(v.v),B('^',u,N(v.v-1))),du));return simplify(B('*',B('^',u,v),B('+',B('*',dv,F('ln',u)),B('*',v,B('/',du,u)))))}if(a.k==='f'){const u=a.args[0],du=derivative(u,x),name=a.name;if(name==='sin')return simplify(B('*',F('cos',u),du));if(name==='cos')return simplify(B('*',{k:'u',op:'-',a:F('sin',u)},du));if(name==='tan')return simplify(B('*',B('/',N(1),B('^',F('cos',u),N(2))),du));if(name==='sqrt')return simplify(B('/',du,B('*',N(2),F('sqrt',u))));if(name==='ln')return simplify(B('/',du,u));if(name==='exp')return simplify(B('*',F('exp',u),du));if(name==='asin')return simplify(B('/',du,F('sqrt',B('-',N(1),B('^',u,N(2))))));if(name==='acos')return simplify({k:'u',op:'-',a:B('/',du,F('sqrt',B('-',N(1),B('^',u,N(2)))))});if(name==='atan')return simplify(B('/',du,B('+',N(1),B('^',u,N(2)))));if(name==='log'&&a.args.length===1)return simplify(B('/',du,B('*',u,N(Math.log(10)))));if(name==='abs')return simplify(B('*',B('/',u,F('abs',u)),du))}throw Error('Derivaci této funkce nelze bezpečně ověřit')}
function varsOf(a,set=new Set()){if(a.k==='v'&&!Object.hasOwn(CONST,a.name))set.add(a.name);if(a.a)varsOf(a.a,set);if(a.b)varsOf(a.b,set);for(const x of a.args||[])varsOf(x,set);return set}
function equivalent(a,b,opts={}){const A=typeof a==='string'?parse(a):a,Bb=typeof b==='string'?parse(b):b,n=Math.max(8,Math.min(40,opts.samples||18)),names=[...new Set([...varsOf(A),...varsOf(Bb)])];if(!names.length){try{const av=val(A),bv=val(Bb);return {equivalent:Number.isFinite(av)&&Number.isFinite(bv)&&Math.abs(av-bv)<=1e-9*Math.max(1,Math.abs(av),Math.abs(bv)),samples:1}}catch{return {equivalent:false,samples:0}}}let good=0;for(let i=0;i<n*3&&good<n;i++){const env={};names.forEach((name,j)=>env[name]=(((i+1)*(j+3)*37)%211-105)/13||.37);try{const x=val(A,env),y=val(Bb,env);if(!Number.isFinite(x)||!Number.isFinite(y))continue;const tol=1e-7*Math.max(1,Math.abs(x),Math.abs(y));if(Math.abs(x-y)>tol)return {equivalent:false,samples:good+1,counterexample:env,left:x,right:y};good++}catch{}}return {equivalent:good>=Math.min(5,n),samples:good}}
function poly2(ast,x='x'){ast=simplify(ast);if(ast.k==='n')return [ast.v,0,0];if(ast.k==='v')return ast.name===x?[0,1,0]:null;if(ast.k==='u'){const p=poly2(ast.a,x);return p&&p.map(v=>-v)}if(ast.k!=='b')return null;const A=poly2(ast.a,x),Bv=poly2(ast.b,x);if(!A||!Bv)return null;if(ast.op==='+'||ast.op==='-')return A.map((v,i)=>v+(ast.op==='+'?1:-1)*Bv[i]);if(ast.op==='*'){const out=[0,0,0,0,0];for(let i=0;i<3;i++)for(let j=0;j<3;j++)out[i+j]+=A[i]*Bv[j];return Math.abs(out[3])+Math.abs(out[4])<1e-12?out.slice(0,3):null}if(ast.op==='/'&&Bv[1]===0&&Bv[2]===0&&Bv[0]!==0)return A.map(v=>v/Bv[0]);if(ast.op==='^'&&ast.b.k==='n'&&ast.b.v===2){const P=poly2(ast.a,x);if(!P||P[2]!==0)return null;return [P[0]*P[0],2*P[0]*P[1],P[1]*P[1]]}return null}
function solveEquation(left,right='0',x='x'){const p=poly2(B('-',parse(left),parse(right)),x);if(!p)return {kind:'unsupported',roots:[]};const [c,b,a]=p;if(Math.abs(a)<1e-12){if(Math.abs(b)<1e-12)return {kind:Math.abs(c)<1e-12?'identity':'none',roots:[]};return {kind:'linear',roots:[-c/b]}}const d=b*b-4*a*c;if(d<-1e-12)return {kind:'quadratic',discriminant:d,roots:[]};if(Math.abs(d)<1e-12)return {kind:'quadratic',discriminant:0,roots:[-b/(2*a)]};const q=Math.sqrt(d);return {kind:'quadratic',discriminant:d,roots:[(-b-q)/(2*a),(-b+q)/(2*a)]}}

function linearForm(ast,names){
 ast=simplify(ast);const zero=()=>Array(names.length).fill(0),add=(A,B,k=1)=>({c:A.c+k*B.c,a:A.a.map((v,i)=>v+k*B.a[i])}),scale=(A,k)=>({c:A.c*k,a:A.a.map(v=>v*k)}),isConst=A=>A.a.every(v=>Math.abs(v)<1e-12);
 if(ast.k==='n')return {c:ast.v,a:zero()};if(ast.k==='v'){if(Object.hasOwn(CONST,ast.name))return {c:CONST[ast.name],a:zero()};const i=names.indexOf(ast.name);if(i<0)return null;const a=zero();a[i]=1;return {c:0,a}}
 if(ast.k==='u'){const A=linearForm(ast.a,names);return A&&scale(A,-1)}if(ast.k!=='b')return null;const A=linearForm(ast.a,names),Bv=linearForm(ast.b,names);if(!A||!Bv)return null;if(ast.op==='+')return add(A,Bv);if(ast.op==='-')return add(A,Bv,-1);if(ast.op==='*'){if(isConst(A))return scale(Bv,A.c);if(isConst(Bv))return scale(A,Bv.c);return null}if(ast.op==='/'&&isConst(Bv)&&Math.abs(Bv.c)>1e-12)return scale(A,1/Bv.c);if(ast.op==='^'&&isConst(Bv)&&Bv.c===1)return A;if(ast.op==='^'&&isConst(Bv)&&Bv.c===0)return {c:1,a:zero()};return null
}
function solveLinearSystem(equations,variables=[]){
 const eqs=(Array.isArray(equations)?equations:[]).map(String).filter(Boolean);if(!eqs.length)return {kind:'unsupported',variables:[],solution:null};let names=(Array.isArray(variables)?variables:[]).map(String).filter(Boolean);if(!names.length){const set=new Set();for(const eq of eqs){const [l,r='0']=eq.split('=');for(const n of varsOf(parse(l)))set.add(n);for(const n of varsOf(parse(r)))set.add(n)}names=[...set]}
 if(!names.length||names.length>8)return {kind:'unsupported',variables:names,solution:null};const M=[];for(const eq of eqs){const pos=eq.indexOf('='),l=pos>=0?eq.slice(0,pos):eq,r=pos>=0?eq.slice(pos+1):'0',f=linearForm(B('-',parse(l),parse(r)),names);if(!f)return {kind:'unsupported',variables:names,solution:null};M.push([...f.a,-f.c])}
 const m=M.length,n=names.length,eps=1e-10;let row=0;const piv=[];for(let col=0;col<n&&row<m;col++){let best=row;for(let r=row+1;r<m;r++)if(Math.abs(M[r][col])>Math.abs(M[best][col]))best=r;if(Math.abs(M[best][col])<eps)continue;[M[row],M[best]]=[M[best],M[row]];const q=M[row][col];for(let c=col;c<=n;c++)M[row][c]/=q;for(let r=0;r<m;r++)if(r!==row&&Math.abs(M[r][col])>=eps){const k=M[r][col];for(let c=col;c<=n;c++)M[r][c]-=k*M[row][c]}piv.push(col);row++}
 for(let r=0;r<m;r++)if(M[r].slice(0,n).every(v=>Math.abs(v)<eps)&&Math.abs(M[r][n])>=eps)return {kind:'inconsistent',variables:names,solution:null};if(piv.length<n)return {kind:'underdetermined',variables:names,solution:null,rank:piv.length};const vals=Array(n).fill(0);for(let r=0;r<piv.length;r++)vals[piv[r]]=M[r][n];return {kind:'unique',variables:names,solution:Object.fromEntries(names.map((v,i)=>[v,vals[i]]))}
}
function toText(a){a=simplify(a);if(a.k==='n')return Number(a.v.toPrecision(14)).toString();if(a.k==='v')return a.name;if(a.k==='u')return '-('+toText(a.a)+')';if(a.k==='f')return a.name+'('+a.args.map(toText).join(',')+')';return '('+toText(a.a)+a.op+toText(a.b)+')'}
export function casParse(src){return parse(src)}
export function casEvaluate(src,vars){return val(typeof src==='string'?parse(src):src,vars)}
export function casEquivalent(a,b,opts){return equivalent(a,b,opts)}
export function casDerivative(src,variable='x'){return toText(derivative(typeof src==='string'?parse(src):src,variable))}
export function casSolveEquation(left,right='0',variable='x'){return solveEquation(left,right,variable)}
export function casSolveLinearSystem(equations,variables=[]){return solveLinearSystem(equations,variables)}
export function casVerify(spec={}){try{if(spec.operation==='equivalent'){const r=equivalent(spec.left,spec.right,spec);return {ok:r.equivalent,...r,message:r.equivalent?'Výrazy jsou ekvivalentní.':'Výrazy nejsou ekvivalentní.'}}if(spec.operation==='derivative'){const got=derivative(parse(spec.expression),spec.variable||'x'),eq=equivalent(got,parse(spec.expected),spec);return {ok:eq.equivalent,equivalent:eq.equivalent,derived:toText(got),samples:eq.samples,message:eq.equivalent?'Derivace ověřena.':'Očekávaná derivace neodpovídá.'};}if(spec.operation==='solve'){const r=solveEquation(spec.left,spec.right||'0',spec.variable||'x'),expected=(spec.expectedRoots||[]).map(Number).sort((a,b)=>a-b),actual=r.roots.map(Number).sort((a,b)=>a-b),match=expected.length===actual.length&&expected.every((v,i)=>Math.abs(v-actual[i])<1e-8*Math.max(1,Math.abs(v)));return {ok:match,match,...r,message:match?'Kořeny ověřeny.':'Kořeny neodpovídají.'}}if(spec.operation==='linear-system'){const r=solveLinearSystem(spec.equations,spec.variables||[]),expected=spec.expected||{},match=r.kind==='unique'&&r.variables.every(k=>Object.hasOwn(expected,k)&&Math.abs(Number(expected[k])-r.solution[k])<1e-8*Math.max(1,Math.abs(r.solution[k])));return {ok:match,match,...r,message:match?'Lineární soustava ověřena.':'Řešení lineární soustavy neodpovídá.'}}if(spec.operation==='evaluate'){const value=val(parse(spec.expression),spec.variables||{}),has=spec.expected!==undefined,match=!has||Math.abs(value-Number(spec.expected))<1e-9*Math.max(1,Math.abs(value),Math.abs(Number(spec.expected)));return {ok:Number.isFinite(value)&&match,value,match,message:Number.isFinite(value)&&match?'Hodnota ověřena.':'Hodnota neodpovídá.'}}return {ok:false,error:'Neznámá CAS operace'}}catch(error){return {ok:false,error:String(error.message||error)}}}
